config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
  root to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
    has_many :reviews, dependent: :destroy
    validates :name, :address, :category, presence: true
    validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :restaurant
    validates :restaurant, :rating, :content, presence: true
    validates :rating, inclusion: { in: (0..5), allow_nil: false }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end
  
  def show
    @reviews = @restaurant.reviews
  end
  
  def new
    @restaurant = Restaurant.new
  end
  
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
    redirect_to restaurant_path(@restaurant)
    else
    render :new
    end
  end
  
  private
  
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end
  
  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
    redirect_to restaurant_path(@restaurant)
    else
    render :new
    end
  end
  
  private
  
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
  
  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">

  <h1 class="text-center">Restaurants</h1>

  <div class="row">

    <% @restaurants.each do |restaurant| %>

    <div class="col-xs-12 col-sm-4">
        <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
        <p><%= restaurant.address %></p>
    </div>

    <% end %>

  </div>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORIES %>
  <%= f.button :submit, :class => "btn btn-primary" %>
<% end %>
<%= link_to "back", restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

    <h1><%= @restaurant.name %></h1>
      <hr>
      <p> Address: <%= @restaurant.address %> </p>
      <hr>
      <p> Phone: <%= @restaurant.phone_number %> </p>
      <hr>
      <p> Category: <%= @restaurant.category %> </p>
      <hr>
    <h4>Reviews: </h4>

      <% @reviews.each do |review| %>
        
        <li> "<%= review.content %>" <i class="fas fa-star"></i> <%= review.rating %></li>
      
      <% end %>

      <br><br>
     
      <%= link_to new_restaurant_review_path(@restaurant) do%>
        <i class ="fa fa-comment"></i><p>Add a review</p>        
      <% end  %>

    </div>
  </div>
      <%= link_to restaurants_path do%>
        <i class ="fas fa-undo"></i><p>Home</p>      
      <% end  %>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>  
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

<%= link_to "Home", restaurants_path %>